## Set of functions used to extract information from datafiles ()either those
## generated in Psychopy or our own transcription files)


# Function to extract information from transcribed file names
extract_fileinfo <- function(fname) {
  mypattern <- "^(\\d+)(_.*)_block_(\\d).*_(\\d+)\\.wav"
  tibble(
    basefile = gsub(mypattern, "\\1\\2", fname),
    ID    = as.numeric(gsub(mypattern, "\\1", fname)),
    block = as.numeric(gsub(mypattern, "\\3", fname)),
    trial = as.numeric(gsub(mypattern, "\\4", fname))
  )
}


# Function to extract the target words for each selected trial.
# It is designed to be used with pmap, with the output of extract_fileinfo()
# as input (each row specifies the function parameters). For pmap(), see
# http://zevross.com/blog/2019/06/11/the-power-of-three-purrr-poseful-iteration-in-r-with-map-pmap-and-imap/
extract_trial_selection <- function(
  basefile, ID, block, trial, path2folder = "data/raw_data/"
  ) {
  df <- read_csv(paste0(path2folder, basefile, ".csv"))
  df %>%
    # select appropriate trial
    filter(
      block.thisN == block - 1,
      word_presentation.thisN == trial
      ) %>%
    # include identifying info provided as arguments
    mutate(participant = ID, block = block, trial = trial) %>%
    # extract relevant info from the csv file
    select(
      participant, block, block_type = BlockType, word1:word4, trial, 
      trial_type = type
      ) %>%
    # convert to long format, 1 row per word in a trial (i.e., 4 rows per trial)
    pivot_longer(word1:word4, names_to = "word", values_to = "verb") %>%
    mutate(word = gsub("word(\\d)", "\\1", word))
}


# extract all names of datafiles generated by PsychoPy that are not obviously invalid
parse_all_datafiles <- function(path) {
	filename <- list.files(path)
	# filter out
	filename <- filename[grepl("*.csv", filename)]  # CSV only
	filename <- filename[! grepl("*excl.csv", filename)]  # marked as excluded by RA
	mypattern <- "^(\\d+)_.*_swe_(202\\d.*)\\.csv"
	# as tibble
	fs <- tibble(
		ID = as.numeric(gsub(mypattern, "\\1", filename)),
		ID_unique = gsub(mypattern, "\\1_\\2", filename),
		DateTime_unformatted = gsub(mypattern, "\\2", filename),
		DateTime = lubridate::ymd_hm(DateTime_unformatted),
		filename = filename
		) %>%
		filter(ID < 980) %>%  # IDs >= 980 were used for internal tests/piloting
		select(-c(ID, DateTime_unformatted)) %>%
		arrange(DateTime)
	fs
}


extract_design_matrix <- function(basefile, path2folder = "data/raw_data/") {
  # path2folder <- "1908_sp13_replic_swe/psychopy_exp/data/"
  mypattern <- "^(\\d+)_.*_swe_(202\\d.*)\\.csv"
  DateTime_unformatted = gsub(mypattern, "\\2", basefile)  # for unique ID
  df <- read_csv(paste0(path2folder, basefile))
  # select and process relevant columns to get design matrix
  df <- df %>%
  	filter(type %in% c("arm", "leg")) %>%  # select only target trials
  	select(
  		ID = participant, block = block.thisN, block_type = BlockType, 
  		trial_block = word_presentation.thisTrialN, trial_type = type,
  		word1:word4, 
  		) %>%
    mutate(
      ID_unique = paste(ID, DateTime_unformatted, sep = "_"),
      trial_block = trial_block + 1,  # trials = 1, 2, ..., 26
      trial_exp = block * 26 + trial_block,  # trial within experiment
      block = block + 1,  # blocks = 1, 2, 3
      ) %>%
    pivot_longer(word1:word4,names_to = "word_pos", values_to = "verb") %>%
    mutate(word_pos = as.numeric(gsub("word(\\d)", "\\1", word_pos))) %>%
    relocate(ID_unique)
  df
}


# function to pre-process the transcriptions file so it can be joined with
# the design matrix
prepare_transcriptions <- function(df) {
  mypattern <- "^(\\d+)_.*swe_(202\\d.*)_block_(\\d).*_(\\d+)\\.wav"
  df <- df %>%
    mutate(
      ID_unique = gsub(mypattern, "\\1_\\2", filename),
      transcr_list = str_split(transcription, " +"),
      trial_block = trial + 1,  # trials = 1, 2, ..., 26
      # replace empty transcriptions (NAs) with empty strings
      transcription = ifelse(is.na(transcription), "", transcription)
      ) %>%
    select(ID_unique, block, trial_block, transcription, transcr_list)
  df
}
